@startuml EventsAndReslationships
class Event {
    +id: int
    +name: string
    +lastExecutionTime: DateTime
    +toBeExecutedTime: DateTime
    +status: EventStatus
    +automaticExecution: boolean
}

    EventRelationship "*" -- "1" Event : from
    EventRelationship "*" -- "1" Event : to

class EventStatus <<data>> {
    +included: boolean
    +pending: boolean
    +enabled: boolean
    +executed: boolean
}

class DateTime <<data>> {
    +date: string
    +time: string
}

class EventRelationship {
    +id: int
    +eventId: int
    +relatedEventId: int
    +eventRelationshipType: EventRelationshipType
    +timeDistance: TimeDistance
}

enum EventRelationshipType {
    CONDITION
    RESPONSE
    INCLUDE
    EXCLUDE
    MILESTONE
}

class TimeDistance <<data>> {
    +days: int
    +hours: int
    +minutes: int
}